server:
  port: 8769

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/

# 查看zuul的监控界面（开发时，配置为*，上线，不要配置）
management:
  endpoints:
    web:
      exposure:
        include: "*"

#配置zuul的路由表
zuul:
  routes:
    api-a: # 自定义的名称
      path: /api/a/**  #拦截的路径
      serviceId: CUSTOMER-SERVICE #匹配的服务

    api-b:
      path: /api/b/**
      serviceId: CUSTOMER-SERVICE-FEIGN